apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend-user
  name: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      service: backend-user
  template:
    metadata:
      labels:
        service: backend-user
    spec:
      containers:
        - image: uchitavietnam/udagram-api-user
          name: backend-user
          imagePullPolicy: Always
          resources:
            requests:
              memory: '1024Mi'
              cpu: '125m'
            limits:
              memory: '2048Mi'
              cpu: '250m'
          env:
            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: JWT_SECRET
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: POSTGRES_HOST
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: POSTGRES_USERNAME
      restartPolicy: Always
